[package]
name = "copy_matching_name_contents"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = "0.4.22"
# tokio = { version = "1.41", features = ["full"] }
chrono = "0.4"
log4rs = "1.3"
clap = "4.5"
